export const Navlinks=[
    {
        name:"Home",
        path:"/",
        showOnNav:true,
        active:true
    },
    {
        name:"Menu",
        path:"#menu-bar",
        showOnNav:true,
    },
    
    {
        name:"Order",
        path:"/user/orders",
        showOnNav:true,
        author:'user',
        protected:true
    },
    {
        name:"Cart",
        path:"/user/cart",
        showOnNav:true,
        author:'user',
        protected:true
    },
    {
        name:"Favourites",
        path:"/user/favourites",
        showOnDrop:true,
        author:'user',
        protected:true
    },
    {
        name:"Custom Pizza",
        path:"/user/custom-pizza",
        showOnDrop:true,
        author:'user',
        protected:true
    },
    {
        name:"Profile",
        path:"/user",
        showOnDrop:true,
        author:'user',
        protected:true
    },
    {
        name:"Orders",
        path:"/admin/orders",
        showOnNav:true,
        author:'admin',
        protected:true
    },
    {
        name:"Inventory",
        path:"/admin/inventory",
        showOnNav:true,
        author:'admin',
        protected:true
    },
    {
        name:"Menu",
        path:"/admin/menu",
        showOnDrop:true,
        author:'admin',
        protected:true
    },
    {
        name:"Offer",
        path:"/admin/offer",
        showOnDrop:true,
        author:'admin',
        protected:true
    },
    {
        name:"Profile",
        path:"/admin",
        showOnDrop:true,
        author:'admin',
        protected:true
    }
    
]